<a href="https://colab.research.google.com/github/devkakeri06/segregation-assignment/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_excel("/content/Google DSC DIT Member Application (Responses) (1).xlsx")
df.head()

,Timestamp,Name,Email ID,Phone Number (WhatsApp),Domain,Unnamed: 5
0,2022-09-06 17:56:49.270,Prathmesh jaiswal,prathmeshjaiswal550@gmail.com,09370359323,"Web Development, Cloud",I agree to the terms
1,2022-09-06 17:57:07.469,Gargee Rangnekar,gargeerangnekar@gmail.com,+919370094904,"Web Development, Android, AI/ ML, Cloud, Cyber...",I agree to the terms
2,2022-09-06 17:57:08.513,Moinuddin shikalgar,moinuddinshikalgar@gmail.com,07249718662,"Web Development, Flutter, Android, Cyber Secur...",I agree to the terms
3,2022-09-06 17:59:18.665,Varun Teli,varunteli4@gmail.com,8855047278.0,"AI/ ML, Competitive Programming",I agree to the terms
4,2022-09-06 17:59:26.726,Khushi Chaudhari,chaudharikhushi67@gmail.com,9373619156.0,"Web Development, Competitive Programming",I agree to the terms

In [3]:
# df['id'] = df.groupby(['Name']).ngroup()
df = df[['Name', 'Email ID', 'Phone Number (WhatsApp)', 'Domain']]
df.head(10)

,Name,Email ID,Phone Number (WhatsApp),Domain
0,Prathmesh jaiswal,prathmeshjaiswal550@gmail.com,09370359323,"Web Development, Cloud"
1,Gargee Rangnekar,gargeerangnekar@gmail.com,+919370094904,"Web Development, Android, AI/ ML, Cloud, Cyber..."
2,Moinuddin shikalgar,moinuddinshikalgar@gmail.com,07249718662,"Web Development, Flutter, Android, Cyber Secur..."
3,Varun Teli,varunteli4@gmail.com,8855047278.0,"AI/ ML, Competitive Programming"
4,Khushi Chaudhari,chaudharikhushi67@gmail.com,9373619156.0,"Web Development, Competitive Programming"
5,Chakradhar Malage,chakumalage2003@gmail.com,8830963898.0,"Web Development, Android, Cloud, Cyber Securit..."
6,Pranali Modi,pranalimodi29@gmail.com,9325442113.0,"Android, AI/ ML, Competitive Programming"
7,SALONI GUPTA,salonigupta.jsr@gmail.com,7070140139.0,"Web Development, Competitive Programming"
8,TANMAY H PHALKE,tanmay2723@gmail.com,8999606633.0,"Web Development, Flutter, Android, AI/ ML, Clo..."
9,Tanvi Yadwadkar,tanvi.yadwadkar03@gmail.com,7066772503.0,"Web Development, Android, AI/ ML"

In [6]:
AIML = df[df['Domain'].str.contains('AI/ ML')]
AIML.head(10)

,Name,Email ID,Phone Number (WhatsApp),Domain
1,Gargee Rangnekar,gargeerangnekar@gmail.com,+919370094904,"Web Development, Android, AI/ ML, Cloud, Cyber..."
3,Varun Teli,varunteli4@gmail.com,8855047278.0,"AI/ ML, Competitive Programming"
6,Pranali Modi,pranalimodi29@gmail.com,9325442113.0,"Android, AI/ ML, Competitive Programming"
8,TANMAY H PHALKE,tanmay2723@gmail.com,8999606633.0,"Web Development, Flutter, Android, AI/ ML, Clo..."
9,Tanvi Yadwadkar,tanvi.yadwadkar03@gmail.com,7066772503.0,"Web Development, Android, AI/ ML"
10,Prasad Patil,prasadspatil3@gmail.com,9146316151.0,"AI/ ML, Competitive Programming"
11,Onkar Vinodrao Wattamwar,onkarwattamwar001@gmail.com,9096912241.0,AI/ ML
13,Yash Khadayate,college.yk@gmail.com,7972699443.0,"AI/ ML, Cloud"
15,Mukund Kishor Dhanwate,mukunddhanwate@gmail.com,7721939329.0,"Web Development, Flutter, Android, AI/ ML, Clo..."
18,Gourisha Verma,gourishaverma2002@gmail.com,7710979669.0,"Web Development, AI/ ML, Competitive Programming"

In [9]:
!pip install xlsxwriter

CLOUD = df[df['Domain'].str.contains('Cloud')]
WEBDEV = df[df['Domain'].str.contains('Web Development')]
# UIUX = df[df['Domain'].str.contains('UI/UX')]
CP = df[df['Domain'].str.contains('Competitive Programming')]
# BLOCKCHAIN = df[df['Domain'].str.contains('Blockchain')]
ANDROID = df[df['Domain'].str.contains('Android')]
# CREATIVE_DESIGN = df[df['Domain'].str.contains('Creative Design')]
# VIDEOEDIT = df[df['Domain'].str.contains('Video Editing')]
# CONTENT = df[df['Domain'].str.contains('Content Writing')]
# PRA = df[df['Domain'].str.contains('PRA')]

FLUTTER = df[df['Domain'].str.contains('Flutter')]
CYBERSEC = df[df['Domain'].str.contains('Cyber Security')]
# PRA = df[df['Domain'].str.contains('PRA')]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.7/dist-packages (3.0.3)

In [ ]:
# df = pd.read_excel("/content/Assignment.xlsx")

In [10]:
with pd.ExcelWriter('Devaansh_Kakeri_Assignment.xlsx') as writer:  # doctest: +SKIP
     df.to_excel(writer, sheet_name='Ass')
     AIML.to_excel(writer, sheet_name='AIML', index=False)
     CLOUD.to_excel(writer, sheet_name='CLOUD', index=False)
     WEBDEV.to_excel(writer, sheet_name='WEBDEV', index=False)
    #  UIUX.to_excel(writer, sheet_name='UIUX', index=False)
     CP.to_excel(writer, sheet_name='CP', index=False)
    #  BLOCKCHAIN.to_excel(writer, sheet_name='BLOCKCHAIN', index=False)
    #  CREATIVE_DESIGN.to_excel(writer, sheet_name='CREATIVE_DESIGN', index=False)
    #  VIDEOEDIT.to_excel(writer, sheet_name='VIDEOEDIT', index=False)
    #  CONTENT.to_excel(writer, sheet_name='CONTENT', index=False)
    #  PRA.to_excel(writer, sheet_name='PRA', index=False)
     ANDROID.to_excel(writer, sheet_name='Android', index=False)
     FLUTTER.to_excel(writer, sheet_name='Flutter', index=False)
     CYBERSEC.to_excel(writer, sheet_name='Cyber Security', index=False)